# dataset
roots: [
  '/home/leo/d/datasets/LibriSpeech/train-clean-100',
  '/home/leo/d/datasets/LibriSpeech/train-clean-360',
  '/home/leo/d/datasets/LibriSpeech/train-other-500',
]
sample_rate: 16000
# Hz, all utterances prepared in roots should be in the same
# sample rate currently, can implement resampling in the future
max_time: 40000
# msec, longer utterances will be trimmed
# maximum time of LibriSpeech is about 36 sec
target_level: -25
# pretrained utterances are first scaled to the same decibel level
noise_proportion: 0.5
# stochastically add gaussian noise to input waveforms
snrs: [3, 6, 9]
# sample a noise level for each noise addition

# preprocessor
win_ms: 25
hop_ms: 10
n_freq: 201
n_mels: 40
n_mfcc: 13

# feature configuration
# feat_type can be: complx, linear, mel, mfcc, phase
input:
  feat_type: mel
  channel: 0
  log: True
  delta: 1
  cmvn: True
target:
  feat_type: linear
  channel: 1
  log: True
  delta: 0
  cmvn: False
